Hex viewer
sindresorhus/Pasteboard-Viewer pull request #31
Opened 2024-05-03 03:18 UTC by davedelong

This adds a hex viewer to Pasteboard Viewer and fixes #24.

This uses the [HexFiend framework](https://github.com/hexfiend/hexfiend) to add a hex viewer to the app, which can be accessed by toggling a picker in the toolbar.

Some things to note:

- This depends on the `package` branch of the HexFiend project, as that is the branch that adds a Package.swift file. It is technically unreleased, although it appears to be fully functional.
- The format of the "extra info" in the toolbar is meant to mimic the format shown in the Hex Fiend app as closely as possible.
- Selection is not preserved when toggling between text and hex modes.

<img width="989" alt="Screenshot 2024-05-02 at 9 10 09 PM" src="https://github.com/sindresorhus/Pasteboard-Viewer/assets/112699/d9f4eb42-4f0f-4e60-bc54-96ffb3b25199">
<img width="989" alt="Screenshot 2024-05-02 at 9 10 21 PM" src="https://github.com/sindresorhus/Pasteboard-Viewer/assets/112699/97625980-7d57-4a55-9f69-71a83a17f291">

2024-05-03 15:38 UTC, sindresorhus commented
Thanks for working on this! This is already looking pretty good.

- You need to if-def it out for iOS.
- The selection needs to be reset when the pasteboard changes.
	- I also think it makes sense to reset the selection when switching between pasteboard items.
- I noticed it's quite slow to select something when viewing an image. Not sure if the problem is the framework or the wrapper code.
- Would be useful to have the text/hex picker in the "View" menu bar menu too, with keyboard shortcuts. But not a requirement for this pull request.

2024-05-03 15:41 UTC, sindresorhus requested changes

2024-05-03 15:41 UTC, sindresorhus commented on Pasteboard Viewer/ContentsScreen.swift
> +	class Coordinator: HFRepresenter, ObservableObject {
```suggestion
	class Coordinator: HFRepresenter {
```

It doesn't look like it's used for anything.

2024-05-03 15:41 UTC, sindresorhus commented on Pasteboard Viewer/ContentsScreen.swift
> +			if bits.contains(.contentValue) || bits.contains(.selectedRanges) {
I would use guard here to reduce nesting.

2024-05-03 15:41 UTC, sindresorhus commented on Pasteboard Viewer/ContentsScreen.swift
> +		}
I would move this to a `hexBodyExtraInfo` getter to improve readability as then each branch could use `return`. And it could also use `guard`.

2024-05-04 02:34 UTC, davedelong commented
> * I noticed it's quite slow to select something when viewing an image. Not sure if the problem is the framework or the wrapper code.

I took a quick look at this in instruments, and from what I can tell there's an identical spike when showing the text view as showing the hex view. I'm reasonably confident that this is down to retrieving the `type.data()` from the pasteboard to provide to the UI. There's probably an optimization that could be made there around caching it once it's been read, so that subsequent calls to `.data()` are instantaneous.

2024-05-04 02:34 UTC, davedelong commented
Besides the hiccup when showing large datas (like images), all the other feedback has been addressed, including adding the ⌘1 and ⌘2 switcher in the View menu. 😃

2024-05-04 02:38 UTC, davedelong commented
(I also confirmed that the branch builds cleanly for iOS)

2024-05-04 06:38 UTC, merged

2024-05-04 06:38 UTC, sindresorhus commented
Looks great 🙌

2024-05-04 07:15 UTC, sindresorhus commented
Update submitted.